---    
- name: destroy ec2 instance(s)
  ec2:
    region: "{{general.region}}"
    image: "{{used_ami_id}}"
    instance_type: t2.micro
    wait: yes
    exact_count: 0
    count_tag:
      Name: "{{ item.key }}"
    instance_tags:
      Name: "{{ item.key }}"
  loop: "{{ ec2.vm | dict2items }}"
  tags: [ webserver ]