# gather info from launched VM instances
---
- name: get instance(s) info
  ec2_instance_info:
    region: "{{general.region}}"
  register: instance_info
  tags: [ ec2_info, webserver, check_ssh, apache ]
  
- copy:
    content: "{{instance_info | to_nice_yaml }}"
    dest: "log/launched_ec2.yml"   
  tags: [always]

#creating dynamic inventory
- name: Add all instance public IPs to host group
  add_host: 
    hostname: "{{ item.public_ip_address }}" 
    groups: ec2hosts
    ansible_ssh_private_key_file: "{{ ec2.key.source }}"
    ansible_ssh_user: ubuntu
  when: item.state.name == "running"
  loop: "{{ instance_info.instances }}"
  tags: [ ec2_info, webserver, check_ssh, apache ]
  