# main ansible playbook to provision instances from dynamic inventory
---
- hosts: webserver
  gather_facts: False
  
  tasks:
    - name: Upgrade apt packages
      become: yes
      apt:
        upgrade: yes
        
    - name: Update cache
      become: yes
      apt:  
        update_cache: yes

    - name: Install Apache on ubuntu
      apt: 
        name: apache2
        state: latest 
      become: yes
      notify: restart apache2

    - name: Copy .htaccess
      copy:
        src: ".htaccess"
        dest: "/var/www/html/.htaccess"
      become: yes
      
    # - name: Print new line in the file
    #   lineinfile:
    #     path: "/etc/apache2/apache2.conf"
    #     insertafter: EOF
    #     line: "XBitHack on"
    #     state: present
    #   become: yes
    
    - name: copy index.html and modify permission
      copy:
        src: "index.html"
        dest: "/var/www/html/index.html"
        mode: a+x
      become: yes
    
  handlers:
    - name: restart apache2
      service:
        name: apache2
        enabled: yes
        state: restarted
      become: yes