---
- name: create Vnet
  azure_rm_virtualnetwork:
    resource_group: "{{ global.resourcegroup }}"
    name: "{{ vnet.name }}"
    address_prefixes_cidr: "{{ vnet.cidr }}"
    state: "{{ global.state }}"
  tags: [ vnet, vm, webserver ]